version: "3.9"
services:
  pdf_miner:
    build: .
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: 'django-insecure-d462upu)4h4fx!8vl1%g+^#rjk)m#y^1tsul89bq^ttgni+9k='
      DEBUG: 'True'
  #     DB_URL: postgres://passthrough:passthrough@35.233.251.211:5432/pdf_miner
  #     DB_HOST: "35.233.251.211"
  #   # volumes:
  #   #   - .:/app
  #   depends_on:
  #     - pdf_miner_db

  # pdf_miner_db:
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: passthrough
  #     POSTGRES_PASSWORD: passthrough
  #     POSTGRES_DB: pdf_miner
