apiVersion: v1
kind: Service
metadata:
  name: pdf-miner-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: pdf-miner # linking to deployment of name pdf-miner
